### ISSUE TITLE
[FE][Feat]: 로고와 상단 인풋

### ISSUE THREAD

**Issue by ddaeunbb** [codestates-seb/seb44_main_018#23]
# Todo
<img width="737" alt="스크린샷 2023-07-03 오후 3 29 54" src="https://github.com/codestates-seb/seb44_main_018/assets/82816029/d8155299-3285-42b5-969c-3e7d1c8b7827">

- [x] 최초 Oauth 로그인 시, `이름`, `이메일` 인풋의 `value` 속성을 채우고 수정하지 못하게 `disabled`로 설정한다.
- [x] 닉네임의 placeholder는 `공백제외 10자 이내로 입력해주세요.` 로 채워준다.
- [x] 중복확인 버튼을 생성한다.
  - [x] 닉네임 인풋의 오른쪽 하단에 위치시킨다.
  - [x] 버튼 디자인은 사진 내용과 유사하게 제작한다.
  - [x] <img width="92" alt="스크린샷 2023-07-03 오후 3 44 05" src="https://github.com/codestates-seb/seb44_main_018/assets/82816029/48a1d479-2003-4aa9-9cf9-60cb8ffeea6d">

- [x] 유저가 닉네임 input에 아무것도 입력하지 않았을 때는 중복확인 버튼을 `disabled`로 설정한다.
- [x] 입력 후, 버튼을 클릭하면 유효성검사를 진행한다.
- [x] 유효하지 않으면 아래와 같이 보여주고, 유효하다면 기존 상태로 냅둔다.
<img width="330" alt="스크린샷 2023-07-03 오후 3 40 34" src="https://github.com/codestates-seb/seb44_main_018/assets/82816029/67f01d81-e450-4631-b777-7450a489984b">
