### ISSUE TITLE
[FE][Feat]: NotFound 페이지

### ISSUE THREAD

**Issue by kd02109** [codestates-seb/seb44_main_018#25]
# Page
<img width="296" alt="image" src="https://github.com/codestates-seb/seb44_main_018/assets/57277708/5fbe2f8d-daaf-492c-a4b3-ae16b6933a76">

# Todo
- [x] 버튼 컴포넌트를 활용해서 유저를 home으로 보내야 합니다.
- [x] home 버튼 클릭시  "/home" 으로 유저를 이동시킵니다.
- [x] Footer 컴포넌트가 있습니다.
