### ISSUE TITLE
[FE][Feat]: MainPage

### ISSUE THREAD

**Issue by kd02109** [codestates-seb/seb44_main_018#26]
# Page
<img width="298" alt="image" src="https://github.com/codestates-seb/seb44_main_018/assets/57277708/7a766bba-a20a-4ef3-a905-911d01547a86">

# Todo
- [x] 로고와, 웹 어플리케이션의 고유 이름이 들어가야 합니다.
- [ ] kakao OAuth가 동작할 수 있도록 작성합니다. 
- [x] kakao OAuth를 클릭한 유저는 추가 회원 정보 기입 페이지로 이동시켜야 합니다.
- [ ] 회원가입을 원치 않는 유저를 위해 게스트 계정 시작 기능을 추가합니다. 게스트로 시작시 해당 유저를 ('/home')으로 이동시킵니다.
- [x] Footer 컴포넌트가 들어가야 합니다.
