### ISSUE TITLE
[FE][Feat]: 산책 탭 클릭 시 로그인 계정과 반려동물 등록 여부 확인

### ISSUE THREAD

**Issue by leejaelll** [codestates-seb/seb44_main_018#27]
# Todo
- [x] Header에서 '산책' 탭을 눌렀을 때, 로그인 유저인지 게스트인지 확인한다. 
<img width="717" alt="스크린샷" src="https://github.com/codestates-seb/seb44_main_018/assets/89183947/9cd19f90-eeef-4298-b483-51d2a9dcead9">

- [x] JWT accessToken이 있으면서 반려동물을 등록한 유저라면(`animalParents:true`) 산책페이지를 렌더링한다. 
- [x] JWT accessToken이 있으면서 반려동물을 등록한 유저가 아니라면 (`animalParents:false`) 반려동물 등록 안내 팝업창을 띄운다. 
<img width="351" alt="스크린샷" src="https://github.com/codestates-seb/seb44_main_018/assets/89183947/5a44b134-b335-4675-a3d2-8afb3de1241e">

- [x] 게스트라면 로그인 안내 팝업창을 띄운다.
<img width="398" alt="스크린샷" src="https://github.com/codestates-seb/seb44_main_018/assets/89183947/38cb8095-e2be-41a1-a447-4b8da81ef68b">
