### ISSUE TITLE
[FE][Feat]: 펫 등록 페이지

### ISSUE THREAD

**Issue by kd02109** [codestates-seb/seb44_main_018#28]
# Page

<img width="473" alt="image" src="https://github.com/codestates-seb/seb44_main_018/assets/57277708/541300a0-2b9e-4b43-8046-e7204b8efa18">

# Todo
- [x] 해당 페이지는 팝업 형태로 사용이 됩니다. 
## 반려동물 프로필 등록
- [x] 반려동물 프로필 등록이 가능합니다. 
- [ ] 반려동물 프로필 선택은 버튼 클릭 이외에 드래그 기능을 허용합니다. 
- [x] 반려동물 프로필은 이미지 자르기 편집 기능을 넣습니다. 

## 인풋 및 텍스트
- [x] 이름은 최소 1글자 이상 10글자 이하입니다. (특수기호는 모두 제외 합니다.) 반려동물 이름은 중복이 가능합니다.
- [x] 나이는 숫자만 받을 수 있습니다.
- [x] 성별 선택은 checkbox로 구현합니다.
- [x] 짧은 자기소개서는 작성 생략이 가능합니다. 최대 작성 글 수는 15자 입니다.
