### ISSUE TITLE
[FE][Feat]: 마이페이지

### ISSUE THREAD

**Issue by ddaeunbb** [codestates-seb/seb44_main_018#29]
# Todo
- [x] 상단의 헤더에 있는 프로필을 클릭하면 `/my-page` 경로로 들어올 수 있게 한다.
<img width="586" alt="스크린샷 2023-07-04 오전 10 35 17" src="https://github.com/codestates-seb/seb44_main_018/assets/82816029/4b2e9c43-9267-4784-a5de-f0031f778f13">

- [x] `/my-page`에 들어오게 되면 헤더의 테두리색이 `#69B783` 으로 변경되게 한다.
- [x] `/my-page`에 들어오게 되면 `/members/{host-member-id}/{guest-member-id}  ex) /1/5` 경로로 GET요청을 해 유저의 정보를 가져온다.
<br><br>

### `animalParents`가 true일 때
<img width="530" alt="스크린샷 2023-07-04 오후 4 15 34" src="https://github.com/codestates-seb/seb44_main_018/assets/82816029/0acea54f-6f15-4c47-b76a-896eac56aaf9">

  - [x] `animalParents` 값에 상관 없이 공통적으로 유저의 아이디, 게시물 개수, 랜선집사 수, 자신이 구독하는 수를 보여주어야한다.
  - [x] 유저닉네임 옆에 설정 아이콘을 클릭하면 `/info/:userId`페이지로 넘어가야한다.
  - [x] 펫의 설정 아이콘을 클릭하면 펫 수정 팝업창이 뜨게 해야한다.
  - [x] 펫의 추가 아이콘을 클릭하면 펫 추가 팝업창이 뜨게 해야한다.
  - [x] 자신이 키우는 동물들의 정보가 적힌 Card 컴포넌트들을 `flex-col`(tailwind) 로 정렬하여 보여주여야한다.
  - [x] Card 컴포넌트에 자신들의 동물들의 데이터를 props로 넘겨주어야한다.
  - [x] 피드게시물을 디폴트로 보여주고, 자신이 올린 피드 게시물들을 컴포넌트들을 4개씩 정렬하여 보여준다.
4개씩 정렬해야하는 피드 카드<img width="145" alt="스크린샷 2023-07-04 오전 10 49 52" src="https://github.com/codestates-seb/seb44_main_018/assets/82816029/f8702ba5-0af7-4022-b4bf-f0c52a058253">

  - [x] 산책게시물 탭을 누르면, 자신이 작성한 산책 게시물 컴포넌트들을 3개씩 정렬하여 보여주여야한다.
  - [x] 산책 게시물 컴포넌트를 클릭하면 `/walkmate/:postId` 페이지로 넘어가야한다. (해당산책게시물페이지)
3개씩 정렬해야하는 게시물 컴포넌트<img width="287" alt="스크린샷 2023-07-04 오전 10 50 00" src="https://github.com/codestates-seb/seb44_main_018/assets/82816029/16a41b2d-4082-4ff6-9efa-65b4684f484c">

  - [x] 댓글게시물 탭을 누르면, 자신이 작성했었던 댓글 리스트들을 보여주여야한다.
  - [x] 댓글게시물 컴포넌트를 클릭하면 `/walkmate/:postId` 페이지로 넘어가야한다. (해당산책게시물페이지)
<img width="277" alt="스크린샷 2023-07-04 오전 10 50 32" src="https://github.com/codestates-seb/seb44_main_018/assets/82816029/c4311d74-f576-4fda-808b-15f8afa141e8">

### `animalParents`가 false일 때
<img width="513" alt="스크린샷 2023-07-04 오전 10 55 04" src="https://github.com/codestates-seb/seb44_main_018/assets/82816029/85ea9ac2-1456-43c9-951b-f3a2b9f2016f">

  - [x] `animalParents` 값에 상관 없이 공통적으로 유저의 아이디, 게시물 개수, 랜선집사 수, 자신이 구독하는 수를 보여주어야한다.
  - [x] 유저닉네임 옆에 설정 아이콘을 클릭하면 `/info/:userId`페이지로 넘어가야한다.
  - [x] 피드게시물을 디폴트로 보여주고, 자신이 올린 피드 게시물들을 컴포넌트들을 4개씩 정렬하여 보여준다.
4개씩 정렬해야하는 피드 카드<img width="145" alt="스크린샷 2023-07-04 오전 10 49 52" src="https://github.com/codestates-seb/seb44_main_018/assets/82816029/f8702ba5-0af7-4022-b4bf-f0c52a058253">
