### ISSUE TITLE
[FE][Feat]: 회원가입 페이지 반려동물 등록

### ISSUE THREAD

**Issue by kd02109** [codestates-seb/seb44_main_018#33]
# Page
<img width="285" alt="image" src="https://github.com/codestates-seb/seb44_main_018/assets/57277708/30116d0d-2be7-4bf8-8d5a-264e68ccf8d6">

# Todo
- [ ] 설정 icon을 클릭하면 해당 반려동물의 설정 팝업을 띄웁니다. 
- [ ] 등록된 반려동물이 있을 시, 반려동물 등록 라벨 아래에 각 반려 동물에 대한 짧은 소개가 컴포넌트로 보여져야 합니다.
- [ ] 등록된 반려동물이 없을 시 아무것도 띄우지 않습니다.
- [ ] 최초 반려동물 등록은 반려동물 등록 라벨의 오른쪽에 위치한 plus 버튼을 통해 반려동물 팝업 창을 띄웁니다.
