### ISSUE TITLE
[FE][Feat]: Welcome pop-up page

### ISSUE THREAD

**Issue by kd02109** [codestates-seb/seb44_main_018#41]
# Page
<img width="419" alt="image" src="https://github.com/codestates-seb/seb44_main_018/assets/57277708/ccd5c654-ec58-4576-923c-225aaa5d0653">

# Todo
- [ ] 최초 회원 가입한 유저만 '/home'에서 팝업 페이지를 보여줍니다.
- [ ] 팝업 페이지에는 반려동물 등록을 안내하는 내용이 포함되어야 합니다.
      - [ ] 반려동물이 등록되어야 산책 페이지에 접근할 수 있다는 것을 알립니다.
      - [ ] 반려 동물 등록을 원한다면 마이페이지로 유저를 이동시켜야 합니다.
