### ISSUE TITLE
[FE][Feat]: 피드 게시물 수정 팝업

### ISSUE THREAD

**Issue by ddaeunbb** [codestates-seb/seb44_main_018#42]
# Todo
<img width="531" alt="스크린샷 2023-07-04 오후 3 23 15" src="https://github.com/codestates-seb/seb44_main_018/assets/82816029/90e53a1d-01d8-482d-b99e-75be538a1ed7">

- [ ] 자신이 작성한 피드 게시물에 수정버튼을 누르면 `feed-posting/:feedId`로 이동되게한다.
- [ ] 자신이 작성한 피드 게시물에 수정버튼을 누르면 게시물 수정 팝업이 뜨게 한다.
- [ ] `/{feed-id}`로 GET요청 하여 게시물의 정보를 가져와 게시물의 사진과 내용 데이터를 미리 채워놓는다.
- [x] 게시물 사진은 캐러셀 형태로 이뤄져야하며, 최대 3개만 이미지가 등록가능하다.
- [x] 이미지 상단에 `'X'` 버튼을 누르면 이미지가 캐러셀에서 삭제되게한다.
- [ ] `'X'`버튼을 누르면 삭제할 이미지 리스트로 담아두어야한다. (요청으로 보내기위해)
- [ ] 이미지를 추가하면 추가할 이미지 데이터 리스트로 담아두어야한다.
- [ ] 수정버튼을 누르면 `/{feed-id}/{member-id}`로 POST요청을 보낸다.
  - POST요청시, request body는 API명세서를 참고한다. (이슈 작성시, 명세서 수정중임)
