### ISSUE TITLE
[FE][Feat]: 산책 페이지 스타일링

### ISSUE THREAD

**Issue by leejaelll** [codestates-seb/seb44_main_018#45]
# Page
<img width="680" alt="스크린샷" src="https://github.com/codestates-seb/seb44_main_018/assets/89183947/d622d6be-b30b-4eeb-bfe0-70c3b80c8552"> 

<img width="299" alt="스크린샷" src="https://github.com/codestates-seb/seb44_main_018/assets/89183947/b4ae5b7c-71a4-46da-85ea-ab5d7782a968">

# Todo
- [x] Heaader 컴포넌트 + 주소선택 컴포넌트 + 게시글 컴포넌트로 구성한다. 

### Responsive Design
- [x] 카드 크기는 데스크탑, 모바일 모두 width,height 동일하다. 
- [x] `display: flex`, `flex-wrap: wrap`으로 구현해 viewport가 줄어들 때마다 column의 개수가 변경되도록 한다. 
- [x] 모바일뷰로 변경되면 헤더컴포넌트가 하단에 위치해야한다.
