### ISSUE TITLE
[FE][Feat]: 피드 팝업 페이지

### ISSUE THREAD

**Issue by ddaeunbb** [codestates-seb/seb44_main_018#46]
# Todo
<img width="712" alt="스크린샷 2023-07-04 오후 3 32 39" src="https://github.com/codestates-seb/seb44_main_018/assets/82816029/8c07c322-a872-4995-a962-d4094811a0bc">

- [ ] 어떠한 유저 페이지에서 피드를 클릭했을 때, 피드페이지로 이동되게 해야한다. `/home/:feedId`
- [ ] 페이지가 이동되면 피드의 정보를 GET요청한다. `/feeds/{feed-id}`
- [ ] 왼쪽은 캐러샐 형식으로 이미지를 채운다, 피드 작성자의 아이디, 피드본문( 10자 이상은 10자 + ••• 로 보여준다.), 더보기 버튼으로 채운다.
- [ ] 더보기 버튼을 누르면 아래에서 위로 올라오듯 본문의 전체를 보여준다.
- [ ] 오른쪽에는 댓글을 모두 보여준다.
- [ ] 댓글 작성자가 본인이라면 아래와 같이 수정과 삭제버튼을 보여준다.
<img width="234" alt="스크린샷 2023-07-04 오후 3 37 46" src="https://github.com/codestates-seb/seb44_main_018/assets/82816029/330ac4a8-16c1-4ec4-bd9a-427186a8d288">

- [ ] 댓글 작성자가 본인이라면 아래와 같이 수정과 삭제버튼을 보여준다.
- [ ] 수정 버튼을 누르면 input창이 뜨고 내용이 채워지게 한다.
<img width="232" alt="스크린샷 2023-07-04 오후 3 41 25" src="https://github.com/codestates-seb/seb44_main_018/assets/82816029/574c8c75-0c95-4bba-b8e7-0b2b7f882953">

- [ ] 수정 버튼을 누르면 `/feeds/comments`로 PATCH요청을 한다.
  - [ ]  request body는 API명세서 확인 (아직 API문서 수정중)
- [ ] 삭제버튼을 누르면 `/feeds/comments/{comment-id}/{member-id}`로 DELETE요청이 가게 한다.
- [ ] 댓글을 달고 등록버튼을 누르면 `/feeds/comments/`로 POST요청을 한다.
  - [ ]  request body ->`memberId`, `feedId` `content`
- 좋아요 버튼을 누르면 `feeds//like/{feed-id}/{member-id}`로 PATCH요청을 보낸다. response body의 `isLike`가 true이면 좋아요를 채우고, false이면 좋아요를 채우지 않는다.

- [ ] 이외에 댓글input 위에 있는 아이콘은 자신이 올린 게시물인지 여부에 따라 삭제와 수정버튼을 보여준다.
- [ ] 삭제버튼을 누르면 삭제할건지에 대한 팝업을 뛰운다.
- [ ] 수정버튼을 누르면 수정팝업을 띄운다.
