### ISSUE TITLE
[FE][Feat]: Button Prop

### ISSUE THREAD

**Issue by kd02109** [codestates-seb/seb44_main_018#47]
# Page
<img width="331" alt="image" src="https://github.com/codestates-seb/seb44_main_018/assets/57277708/beceef7b-f895-4adf-af36-3ea43642468c">

# Todo
- [x] 버튼의 크기는 총 세가지 단위로 구분합니다. (lg, md, sm)
- [x] prop은 버튼의 value로 활용될 text와 background 색을 결정할 isGreen을 받아야 합니다. 
- [x] prop으로 각 버튼이 redirect하는 path를 받아야 합니다.

**Comment by kd02109** [comment]
done
