### ISSUE TITLE
 [FE][Feat]: Header Component

### ISSUE THREAD

**Issue by kd02109** [codestates-seb/seb44_main_018#50]
# Component
<img width="434" alt="image" src="https://github.com/codestates-seb/seb44_main_018/assets/57277708/bab93ac8-4fa2-4dc6-8838-df9dd5fd1702">

---
# Todo
- [ ] 로그인한 유저와, 게스트 유저에게 보이는 Header의 성능은 각자 다르다. 
- [ ] 홈`/home` , 산책 `/walkmate`, 포스트 `/feed-posting` 으로 router를 설정한다. 
- [ ] user profile은 `/my-page`로 routing 한다.
- [ ] 해당 페이지에 있다면, 해당하는 Nav를 `#69B783` 색으로 강조한다.
- [ ] 로그인 버튼 클릭시 `/`로 이동한다.
- [ ] 로그아웃 버튼 클릭시 서버와 논의하여 로그아웃 방식을 결정한다.
