### ISSUE TITLE
[FE][Feat]: Profile Component

### ISSUE THREAD

**Issue by leejaelll** [codestates-seb/seb44_main_018#51]
# Component
<img width="340" alt="스크린샷" src="https://github.com/codestates-seb/seb44_main_018/assets/89183947/ceec8038-53c4-4e07-a8cf-62134b3016d1">

# Todo

- [ ] props로 size, url, isGreened를 넘겨준다.
- [ ] size는 lg, md, sm로 구성한다. 
  - [ ] lg: 135 x 135
  - [ ] md: 52 x 52
  - [ ] sm: 32 x 32 
- [ ] isGreened는 Boolean 값으로 전달한다. 
  - [ ] true: `border: 2px solid 69B783`
  - [ ] false: `border: 1px solid D4D4D8`
