### ISSUE TITLE
[FE][Feat]: 게시물 피드 컴포넌트

### ISSUE THREAD

**Issue by ddaeunbb** [codestates-seb/seb44_main_018#52]
# Todo
<img width="267" alt="스크린샷 2023-07-04 오후 5 37 44" src="https://github.com/codestates-seb/seb44_main_018/assets/82816029/4d7ae66c-ed65-49e8-ae58-bc54f9702b86">

- [x] 네모박스 컴포넌트와, 옆에 붙은 nav 컴포넌트를 나눠 2개로 제작해야한다.
- [x] 네모 박스 컴포넌트는 border-radius 28로 설정한다. tailwind: `rounded-[28px]`
- [x] 네모 박스 컴포넌트 안에, 유저의 프로필, 아이디 그리고 본문 내용이 들어갈 수 있게 설정해야한다.
  - 유저 프로필은 크기는 32px이다. tailwind `w-8` `h-8` / 모양은 완전히 원형으로 넣는다.
  - 유저 아이디의 폰트 크기는 12px로 들어간다. tailwind: `text-xs` 굵기는 tailwind: `font-semibold`
  - 본문 텍스트 크기도 `text-xs`
- [x] nav 컴포넌트는 props로 `direction`:(col, row) `inPerson`:(true, false)(본인이라는 뜻) 2개의 값을 받는다.
  -  `direction`이 col이면 tailwind: `flex-col`을 적용한다. 반대로 row이면 `flew-row`를 적용한다.
  - `inPerson`이 true이면 수정과 삭제 버튼이 보이게한다. false이면 3가지 버튼만 보이게한다.(좋아요, 댓글, 공유)
  - 아이콘의 크기는 18px로 설정한다. 텍스트라면`text-lg`로, 이미지라면 `w-[18px]`로 설정하면된다.
