### ISSUE TITLE
[FE][Feat]: WalkCard Component

### ISSUE THREAD

**Issue by leejaelll** [codestates-seb/seb44_main_018#55]
# Component

<img width="349" alt="스크린샷" src="https://github.com/codestates-seb/seb44_main_018/assets/89183947/7ece1e3b-0cee-4c71-bb0e-183362c65346">

# Todo
- [ ] props로 isClosed 를 넘겨준다. 
- [ ] isClosed가 true이면 모집이 완료된 상태이다. 
 - [ ] `background-color: #171717 opacity: 0.7`
 - [ ]  `<div>모집완료</div>` 렌더링
- [ ] isClosed가 true이면 모집 중인 상태이다. 
 - [ ] `background-color: #fffff `
 - [ ]  `<div>모집완료</div>` 렌더링하지 않음

**Comment by kd02109** [comment]
done!
