### ISSUE TITLE
[FE][Feat]: 댓글 컴포넌트

### ISSUE THREAD

**Issue by kd02109** [codestates-seb/seb44_main_018#56]
# Component
<img width="200" alt="image" src="https://github.com/codestates-seb/seb44_main_018/assets/57277708/4c017388-df63-4a7e-a713-788b66709b99">
<img width="440" alt="image" src="https://github.com/codestates-seb/seb44_main_018/assets/57277708/58a7e378-22d0-4aef-9097-7fb55ed84a79">
<img width="200" alt="image" src="https://github.com/codestates-seb/seb44_main_018/assets/57277708/62108e74-1c00-4c48-a912-daa298a10d94">

# Todo
- [ ] 피드 게시물 댓글 리스트, 산책 게시물 상세 페이지 댓글 리스트에 사용된다.
- [ ] 해당 유저가 작성한 댓글일 경우 수정 삭제 버튼이 보여야 한다. 
- [ ] Prop으로 유저프로필, 유저닉네임, 생성시간, text를 전달해야 한다. 
- [ ] 수정 버튼을 클릭시 span을 input 창으로 변경하고 이전의 text 값이 value로 설정되어야 한다. 
- [ ] 삭제 버튼을 클릭시 팝업을 띄우고 삭제를 진행한다. 
- [ ] 유저 프로필을 클릭하면 해당 유저의 유저 페이지로 이동할 수 있어야 한다.
